server:
  port: 9900
  
spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      default-filters:
      - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true      
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
            
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
            
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/microservice-realm
        registration:
          spring-cloud-gatewayclient:
            client-id: spring-cloud-gateway-client
            client-secret: c8cbea01-64be-405f-8e40-2aea41f0e8bf
            provider: keycloak
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9900/login/oauth2/code/spring-cloud-gateway-client

            
            

        
eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true 
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
